  
 pipeline {
  agent none
  stages {
    stage('get code from source code') {
       agent {
                label 'master'
            }
      
      steps {
                sh 'ls '
                cleanWs()
                sh 'ls'
      }
       post {
                always {
                    sh 'echo "Pull source code complete"'
                }
           }
    }

    stage('Build docker image') {
      //parallel {
        stage('Test') {
          steps {
            sh "${params.Env}-${env.BUILD_NUMBER}~"
        //  }
        }

        stage('Integration Test') {
          steps {
            echo 'start integration test '
            timeout(time: 90) {
              echo 'start performance testing after timeout'
            }

          }
        }

        stage('Performance Test') {
          steps {
            echo 'Carryout the q.a test '
          }
        }

      }
    }

    stage('Deploy') {
      when {
        branch 'master'
      }
      steps {
        echo 'Deploying the application....'
        input(message: 'Deploy?', ok: 'Yes')
      }
    }

  }
}
