pipeline {
  agent any
  parameters {
        string(name: 'Env', defaultValue: 'dev', description: 'Current environment')
        string(name: 'Environment', defaultValue: 'Development', description: 'Running environment')
        string(name: 'Eks', defaultValue: 'eks', description: 'eks database')
        string(name: 'cicdPath', defaultValue: 'cicd', description: 'CICD directory path')
        string(name: 'ProjectPath', defaultValue: 'user', description: 'Project path')
                }
  stages {
    stage('Build') {
      steps {
        echo 'Building the application...'
      }
    }

    stage('Test') {
      parallel {
        stage('Test') {
          steps {
            echo 'Testing the application...'
          }
        }

        stage('Integration Test') {
          steps {
            echo 'start integration test '
            timeout(time: 90) {
              echo 'start performance testing after timeout'
            }

          }
        }

        stage('Performance Test') {
          steps {
                    dir(path: "${params.ProjectPath}") {
                    sh 'ls -la'
                    sh "${params.Env}-${env.BUILD_NUMBER}~"
                     
                
          }
        }

      }
    }

    stage('Deploy') {
      when {
        branch 'master'
      }
      steps {
        echo 'Deploying the application....'
        input(message: 'Deploy?', ok: 'Yes')
      }
    }

  }
}
